#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <esp_adc/adc_oneshot.h>

// ES8311 audio codec
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_WS GPIO_NUM_3
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_2
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_4

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_10
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_7
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC

// CellWise CW2017 battery gauge, sharing the codec I2C bus.
#define BATTERY_CW2017_ADDR 0x63

// Three keys share GPIO0 / ADC1 channel 0 through a resistor ladder.
#define BUTTON_ADC_UNIT ADC_UNIT_1
#define BUTTON_ADC_CHANNEL ADC_CHANNEL_0

// ST7789P3 240x320 portrait display
#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_SPI_SCK_PIN GPIO_NUM_8
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_9
#define DISPLAY_SPI_CS_PIN GPIO_NUM_1
#define DISPLAY_DC_PIN GPIO_NUM_20
#define DISPLAY_RESET_PIN GPIO_NUM_NC

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define SEARCH_IMAGE_FLIP_X false
#define SEARCH_IMAGE_FLIP_Y false
#define DISPLAY_INVERT_COLOR true

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_21
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define BUILTIN_LED_GPIO GPIO_NUM_NC

#endif  // _BOARD_CONFIG_H_
